# Build Stage
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY . .
RUN go build -o cart-service main.go

# Run Stage
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/cart-service .
EXPOSE 8080
CMD ["./cart-service"]
